package com.myspace.insect;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class INSECT implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("type")
	private java.lang.String type;

	@org.kie.api.definition.type.Label(value = "product_code")
	private java.lang.String product_code;

	public INSECT() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getProduct_code() {
		return this.product_code;
	}

	public void setProduct_code(java.lang.String product_code) {
		this.product_code = product_code;
	}

	public INSECT(java.lang.String id, java.lang.String name,
			java.lang.String type, java.lang.String product_code) {
		this.id = id;
		this.name = name;
		this.type = type;
		this.product_code = product_code;
	}

}