package com.myspace.insect;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class INSECT implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "type")
	private java.lang.String type;

	public INSECT() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public INSECT(java.lang.String id, java.lang.String name, java.lang.String type) {
		this.id = id;
		this.name = name;
		this.type = type;
	}

}