package com.myspace.insect;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class packageTest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public packageTest() {
    }




}